name: python

on: [push]

jobs:
  snake:
    runs-on: rockylinux:9
    env:
      ENVIRONMENT: DEVELPMENT
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9' 
      - run: |
          python my_script.py
          python --version
          echo "$ENVIRONMENT"
